use crate::objects::*;
use crate::vm::*;
/// Ninja backend: generates build.ninja from the interpreter's build data.
use std::collections::HashMap;
use std::fmt::Write;
use std::path::Path;

pub struct NinjaBackend {
    pub source_root: String,
    pub build_root: String,
}

impl NinjaBackend {
    pub fn new(source_root: &str, build_root: &str) -> Self {
        Self {
            source_root: source_root.to_string(),
            build_root: build_root.to_string(),
        }
    }

    pub fn generate(
        &self,
        build_data: &BuildData,
        project: &ProjectInfo,
    ) -> Result<String, String> {
        let mut out = String::new();
        writeln!(
            out,
            "# This file is autogenerated by rust-meson. Do not edit."
        )
        .unwrap();
        writeln!(out, "ninja_required_version = 1.8.2").unwrap();
        writeln!(out).unwrap();

        // Rules
        self.write_rules(&mut out, project)?;

        // Build edges for each target
        for target in &build_data.targets {
            self.write_target(&mut out, target, build_data)?;
        }

        // Custom targets
        for ct in &build_data.custom_targets {
            self.write_custom_target(&mut out, ct)?;
        }

        // Configure files
        for cf in &build_data.configure_files {
            self.write_configure_file(&mut out, cf)?;
        }

        // Aliases
        self.write_aliases(&mut out, build_data)?;

        // Test targets
        self.write_test_targets(&mut out, build_data)?;

        // Install target
        self.write_install_target(&mut out, build_data)?;

        // Default targets
        self.write_defaults(&mut out, build_data)?;

        Ok(out)
    }

    fn write_rules(&self, out: &mut String, project: &ProjectInfo) -> Result<(), String> {
        // C compiler rule
        if project.languages.iter().any(|l| l == "c" || l == "objc") {
            writeln!(out, "rule c_COMPILER").unwrap();
            writeln!(
                out,
                "  command = cc $ARGS -MD -MQ $out -MF $DEPFILE -o $out -c $in"
            )
            .unwrap();
            writeln!(out, "  deps = gcc").unwrap();
            writeln!(out, "  depfile = $DEPFILE").unwrap();
            writeln!(out, "  description = Compiling C object $out").unwrap();
            writeln!(out).unwrap();
        }

        // C++ compiler rule
        if project
            .languages
            .iter()
            .any(|l| l == "cpp" || l == "c++" || l == "objcpp")
        {
            writeln!(out, "rule cpp_COMPILER").unwrap();
            writeln!(
                out,
                "  command = c++ $ARGS -MD -MQ $out -MF $DEPFILE -o $out -c $in"
            )
            .unwrap();
            writeln!(out, "  deps = gcc").unwrap();
            writeln!(out, "  depfile = $DEPFILE").unwrap();
            writeln!(out, "  description = Compiling C++ object $out").unwrap();
            writeln!(out).unwrap();
        }

        // Rust compiler rule
        if project.languages.iter().any(|l| l == "rust") {
            writeln!(out, "rule rust_COMPILER").unwrap();
            writeln!(
                out,
                "  command = rustc $ARGS --emit dep-info=$DEPFILE,link=$out $in"
            )
            .unwrap();
            writeln!(out, "  deps = gcc").unwrap();
            writeln!(out, "  depfile = $DEPFILE").unwrap();
            writeln!(out, "  description = Compiling Rust target $out").unwrap();
            writeln!(out).unwrap();
        }

        // Fortran compiler rule
        if project.languages.iter().any(|l| l == "fortran") {
            writeln!(out, "rule fortran_COMPILER").unwrap();
            writeln!(out, "  command = gfortran $ARGS -o $out -c $in").unwrap();
            writeln!(out, "  description = Compiling Fortran object $out").unwrap();
            writeln!(out).unwrap();
        }

        // D compiler rule
        if project.languages.iter().any(|l| l == "d") {
            writeln!(out, "rule d_COMPILER").unwrap();
            writeln!(out, "  command = ldc2 $ARGS -of=$out -c $in").unwrap();
            writeln!(out, "  description = Compiling D object $out").unwrap();
            writeln!(out).unwrap();
        }

        // Vala compiler rule
        if project.languages.iter().any(|l| l == "vala") {
            writeln!(out, "rule vala_COMPILER").unwrap();
            writeln!(out, "  command = valac $ARGS -C $in").unwrap();
            writeln!(out, "  description = Compiling Vala source $out").unwrap();
            writeln!(out).unwrap();
        }

        // Linker rules
        writeln!(out, "rule c_LINKER").unwrap();
        writeln!(out, "  command = cc $ARGS -o $out $in $LINK_ARGS").unwrap();
        writeln!(out, "  description = Linking target $out").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "rule cpp_LINKER").unwrap();
        writeln!(out, "  command = c++ $ARGS -o $out $in $LINK_ARGS").unwrap();
        writeln!(out, "  description = Linking target $out").unwrap();
        writeln!(out).unwrap();

        // Static linker
        writeln!(out, "rule STATIC_LINKER").unwrap();
        writeln!(out, "  command = rm -f $out && ar rcs $out $in").unwrap();
        writeln!(out, "  description = Linking static target $out").unwrap();
        writeln!(out).unwrap();

        // Custom command
        writeln!(out, "rule CUSTOM_COMMAND").unwrap();
        writeln!(out, "  command = $COMMAND").unwrap();
        writeln!(out, "  description = $DESC").unwrap();
        writeln!(out, "  restat = 1").unwrap();
        writeln!(out).unwrap();

        // Custom command with depfile
        writeln!(out, "rule CUSTOM_COMMAND_DEP").unwrap();
        writeln!(out, "  command = $COMMAND").unwrap();
        writeln!(out, "  description = $DESC").unwrap();
        writeln!(out, "  deps = gcc").unwrap();
        writeln!(out, "  depfile = $DEPFILE").unwrap();
        writeln!(out, "  restat = 1").unwrap();
        writeln!(out).unwrap();

        // Regenerate rule
        writeln!(out, "rule REGENERATE_BUILD").unwrap();
        writeln!(
            out,
            "  command = meson setup --reconfigure {} {}",
            self.source_root, self.build_root
        )
        .unwrap();
        writeln!(out, "  description = Regenerating build files.").unwrap();
        writeln!(out, "  generator = 1").unwrap();
        writeln!(out).unwrap();

        Ok(())
    }

    fn write_target(
        &self,
        out: &mut String,
        target: &BuildTarget,
        build_data: &BuildData,
    ) -> Result<(), String> {
        let target_dir = if target.subdir.is_empty() {
            String::new()
        } else {
            format!("{}/", target.subdir)
        };

        let mut object_files = Vec::new();
        let mut order_deps = Vec::new();

        // Determine language for compile rule
        let lang = self.detect_target_language(target);
        let compile_rule = format!("{}_COMPILER", lang);

        // Compile each source file
        for source in &target.sources {
            if source.starts_with("<generated:") {
                // Generated source — add as order dependency
                continue;
            }

            let source_path = if target.subdir.is_empty() {
                format!("{}/{}", self.source_root, source)
            } else {
                format!("{}/{}/{}", self.source_root, target.subdir, source)
            };

            let obj_name = source.replace('/', "_").replace('.', "_");
            let obj_path = format!("{}{}_{}.o", target_dir, target.name, obj_name);

            // Collect compile args
            let mut args = Vec::new();
            if target.implicit_include_directories {
                args.push(format!("-I{}", self.source_root));
                if !target.subdir.is_empty() {
                    args.push(format!("-I{}/{}", self.source_root, target.subdir));
                }
                args.push(format!("-I{}", self.build_root));
            }
            for inc in &target.include_dirs {
                args.push(format!("-I{}/{}", self.source_root, inc));
            }

            // Language-specific args
            match lang.as_str() {
                "c" => args.extend(target.c_args.iter().cloned()),
                "cpp" => args.extend(target.cpp_args.iter().cloned()),
                "rust" => args.extend(target.rust_args.iter().cloned()),
                _ => {}
            }

            // Dependency compile args
            for dep in &target.dependencies {
                if let Object::Dependency(d) = dep {
                    args.extend(d.compile_args.iter().cloned());
                    for inc in &d.include_dirs {
                        args.push(format!("-I{}", inc));
                    }
                }
            }

            let depfile = format!("{}.d", obj_path);

            writeln!(out, "build {}: {} {}", obj_path, compile_rule, source_path).unwrap();
            writeln!(out, "  DEPFILE = {}", depfile).unwrap();
            if !args.is_empty() {
                writeln!(out, "  ARGS = {}", args.join(" ")).unwrap();
            }
            writeln!(out).unwrap();

            object_files.push(obj_path);
        }

        // Link step
        let output_path = format!("{}{}", target_dir, target.output_name);

        match target.target_type {
            TargetType::Executable => {
                let link_rule = format!("{}_LINKER", lang);
                let mut link_args = Vec::new();

                // Add library link args
                for dep in &target.dependencies {
                    if let Object::Dependency(d) = dep {
                        link_args.extend(d.link_args.iter().cloned());
                    }
                }
                link_args.extend(target.link_args.iter().cloned());

                // Link with other targets
                let mut link_with_paths = Vec::new();
                for lw in &target.link_with {
                    if let Object::BuildTarget(t) = lw {
                        let lw_dir = if t.subdir.is_empty() {
                            String::new()
                        } else {
                            format!("{}/", t.subdir)
                        };
                        link_with_paths.push(format!(
                            "{}{}",
                            lw_dir,
                            t.outputs.first().unwrap_or(&t.name)
                        ));
                        order_deps.push(format!(
                            "{}{}",
                            lw_dir,
                            t.outputs.first().unwrap_or(&t.name)
                        ));
                    }
                }

                if !target.build_rpath.is_empty() {
                    link_args.push(format!("-Wl,-rpath,{}", target.build_rpath));
                }
                if !target.install_rpath.is_empty() && target.install {
                    link_args.push(format!("-Wl,-rpath,{}", target.install_rpath));
                }

                let mut inputs: Vec<String> = object_files.clone();
                inputs.extend(link_with_paths);

                write!(
                    out,
                    "build {}: {} {}",
                    output_path,
                    link_rule,
                    inputs.join(" ")
                )
                .unwrap();
                if !order_deps.is_empty() {
                    write!(out, " || {}", order_deps.join(" ")).unwrap();
                }
                writeln!(out).unwrap();
                if !link_args.is_empty() {
                    writeln!(out, "  LINK_ARGS = {}", link_args.join(" ")).unwrap();
                }
                writeln!(out).unwrap();
            }
            TargetType::StaticLibrary => {
                write!(
                    out,
                    "build {}: STATIC_LINKER {}",
                    output_path,
                    object_files.join(" ")
                )
                .unwrap();
                writeln!(out).unwrap();
                writeln!(out).unwrap();
            }
            TargetType::SharedLibrary | TargetType::SharedModule => {
                let link_rule = format!("{}_LINKER", lang);
                let mut link_args = vec!["-shared".to_string()];

                if target.target_type == TargetType::SharedLibrary {
                    link_args.push(format!("-Wl,-soname,{}", target.output_name));
                }

                for dep in &target.dependencies {
                    if let Object::Dependency(d) = dep {
                        link_args.extend(d.link_args.iter().cloned());
                    }
                }
                link_args.extend(target.link_args.iter().cloned());

                let pic_arg = if target.pic.unwrap_or(true) {
                    " -fPIC"
                } else {
                    ""
                };

                write!(
                    out,
                    "build {}: {} {}",
                    output_path,
                    link_rule,
                    object_files.join(" ")
                )
                .unwrap();
                writeln!(out).unwrap();
                writeln!(out, "  LINK_ARGS = {}", link_args.join(" ")).unwrap();
                if !pic_arg.is_empty() {
                    writeln!(out, "  ARGS = {}", pic_arg.trim()).unwrap();
                }
                writeln!(out).unwrap();
            }
            _ => {}
        }

        Ok(())
    }

    fn write_custom_target(&self, out: &mut String, ct: &CustomTarget) -> Result<(), String> {
        let target_dir = if ct.subdir.is_empty() {
            String::new()
        } else {
            format!("{}/", ct.subdir)
        };

        let outputs: Vec<String> = ct
            .output
            .iter()
            .map(|o| format!("{}{}", target_dir, o))
            .collect();

        let inputs: Vec<String> = ct
            .input
            .iter()
            .map(|i| {
                if Path::new(i).is_absolute() {
                    i.clone()
                } else if ct.subdir.is_empty() {
                    format!("{}/{}", self.source_root, i)
                } else {
                    format!("{}/{}/{}", self.source_root, ct.subdir, i)
                }
            })
            .collect();

        // Substitute placeholders in command
        let mut command_parts = Vec::new();
        for part in &ct.command {
            let substituted = part
                .replace("@INPUT@", &inputs.join(" "))
                .replace("@OUTPUT@", &outputs.join(" "))
                .replace("@SOURCE_ROOT@", &self.source_root)
                .replace("@BUILD_ROOT@", &self.build_root)
                .replace(
                    "@CURRENT_SOURCE_DIR@",
                    &if ct.subdir.is_empty() {
                        self.source_root.clone()
                    } else {
                        format!("{}/{}", self.source_root, ct.subdir)
                    },
                )
                .replace("@DEPFILE@", &format!("{}{}.d", target_dir, ct.name))
                .replace(
                    "@PLAINNAME@",
                    &ct.input
                        .first()
                        .map(|i| {
                            Path::new(i)
                                .file_name()
                                .unwrap_or_default()
                                .to_string_lossy()
                                .to_string()
                        })
                        .unwrap_or_default(),
                )
                .replace(
                    "@BASENAME@",
                    &ct.input
                        .first()
                        .map(|i| {
                            Path::new(i)
                                .file_stem()
                                .unwrap_or_default()
                                .to_string_lossy()
                                .to_string()
                        })
                        .unwrap_or_default(),
                );

            // Handle @INPUT0@, @OUTPUT0@, etc.
            let mut s = substituted;
            for (i, input) in inputs.iter().enumerate() {
                s = s.replace(&format!("@INPUT{}@", i), input);
            }
            for (i, output) in outputs.iter().enumerate() {
                s = s.replace(&format!("@OUTPUT{}@", i), output);
            }
            command_parts.push(s);
        }

        let rule = if ct.depfile.is_some() {
            "CUSTOM_COMMAND_DEP"
        } else {
            "CUSTOM_COMMAND"
        };

        write!(
            out,
            "build {}: {} {}",
            outputs.join(" "),
            rule,
            inputs.join(" ")
        )
        .unwrap();
        writeln!(out).unwrap();
        writeln!(out, "  COMMAND = {}", shell_escape_command(&command_parts)).unwrap();
        writeln!(out, "  DESC = Generating {}", ct.name).unwrap();
        if let Some(ref depfile) = ct.depfile {
            writeln!(out, "  DEPFILE = {}{}", target_dir, depfile).unwrap();
        }
        if ct.build_always_stale {
            writeln!(out, "  restat = 0").unwrap();
        }
        writeln!(out).unwrap();

        Ok(())
    }

    fn write_configure_file(&self, out: &mut String, cf: &ConfigureFile) -> Result<(), String> {
        let target_dir = if cf.subdir.is_empty() {
            String::new()
        } else {
            format!("{}/", cf.subdir)
        };
        let output_path = format!("{}{}", target_dir, cf.output);

        // Configuration file generation is done at configure time, not build time.
        // We generate a build edge that copies/generates the file.
        if let Some(ref input) = cf.input {
            let input_path = if cf.subdir.is_empty() {
                format!("{}/{}", self.source_root, input)
            } else {
                format!("{}/{}/{}", self.source_root, cf.subdir, input)
            };
            writeln!(out, "build {}: CUSTOM_COMMAND {}", output_path, input_path).unwrap();
            writeln!(out, "  COMMAND = cp {} {}", input_path, output_path).unwrap();
            writeln!(out, "  DESC = Generating {}", cf.output).unwrap();
            writeln!(out).unwrap();
        }

        Ok(())
    }

    fn write_aliases(&self, out: &mut String, build_data: &BuildData) -> Result<(), String> {
        // Build aliases for run targets
        for rt in &build_data.run_targets {
            let phony_name = format!("run_{}", rt.name);
            writeln!(out, "build {}: phony", phony_name).unwrap();
            writeln!(out).unwrap();
        }
        Ok(())
    }

    fn write_test_targets(&self, out: &mut String, build_data: &BuildData) -> Result<(), String> {
        if !build_data.tests.is_empty() {
            let test_deps: Vec<String> = build_data
                .tests
                .iter()
                .filter_map(|t| {
                    if let Object::BuildTarget(ref bt) = t.exe {
                        let dir = if bt.subdir.is_empty() {
                            String::new()
                        } else {
                            format!("{}/", bt.subdir)
                        };
                        Some(format!("{}{}", dir, bt.outputs.first().unwrap_or(&bt.name)))
                    } else {
                        None
                    }
                })
                .collect();

            if !test_deps.is_empty() {
                writeln!(
                    out,
                    "build meson-test-prereq: phony {}",
                    test_deps.join(" ")
                )
                .unwrap();
                writeln!(out).unwrap();
            }
        }
        Ok(())
    }

    fn write_install_target(&self, out: &mut String, build_data: &BuildData) -> Result<(), String> {
        let mut install_deps = Vec::new();

        for target in &build_data.targets {
            if target.install {
                let dir = if target.subdir.is_empty() {
                    String::new()
                } else {
                    format!("{}/", target.subdir)
                };
                install_deps.push(format!("{}{}", dir, target.output_name));
            }
        }

        if !install_deps.is_empty() {
            writeln!(
                out,
                "build meson-install-prereq: phony {}",
                install_deps.join(" ")
            )
            .unwrap();
            writeln!(out).unwrap();
        }
        Ok(())
    }

    fn write_defaults(&self, out: &mut String, build_data: &BuildData) -> Result<(), String> {
        let mut defaults = Vec::new();
        for target in &build_data.targets {
            if target.build_by_default {
                let dir = if target.subdir.is_empty() {
                    String::new()
                } else {
                    format!("{}/", target.subdir)
                };
                defaults.push(format!("{}{}", dir, target.output_name));
            }
        }
        for ct in &build_data.custom_targets {
            if ct.build_by_default {
                let dir = if ct.subdir.is_empty() {
                    String::new()
                } else {
                    format!("{}/", ct.subdir)
                };
                for o in &ct.output {
                    defaults.push(format!("{}{}", dir, o));
                }
            }
        }

        if !defaults.is_empty() {
            writeln!(out, "default {}", defaults.join(" ")).unwrap();
        }

        Ok(())
    }

    fn detect_target_language(&self, target: &BuildTarget) -> String {
        // Check source file extensions
        let has_cpp = target.sources.iter().any(|s| {
            s.ends_with(".cpp") || s.ends_with(".cc") || s.ends_with(".cxx") || s.ends_with(".C")
        });
        let has_rust = target.sources.iter().any(|s| s.ends_with(".rs"));
        let has_fortran = target
            .sources
            .iter()
            .any(|s| s.ends_with(".f") || s.ends_with(".f90") || s.ends_with(".f95"));
        let has_d = target.sources.iter().any(|s| s.ends_with(".d"));
        let has_vala = target.sources.iter().any(|s| s.ends_with(".vala"));

        if has_rust {
            "rust".to_string()
        } else if has_cpp {
            "cpp".to_string()
        } else if has_fortran {
            "fortran".to_string()
        } else if has_d {
            "d".to_string()
        } else if has_vala {
            "vala".to_string()
        } else {
            "c".to_string()
        }
    }
}

fn shell_escape_command(parts: &[String]) -> String {
    parts
        .iter()
        .map(|p| {
            if p.contains(' ')
                || p.contains('\'')
                || p.contains('"')
                || p.contains('$')
                || p.contains('\\')
            {
                format!("'{}'", p.replace('\'', "'\\''"))
            } else {
                p.clone()
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

/// Write the introspection data files in the build directory
pub fn write_introspection(
    build_root: &str,
    build_data: &BuildData,
    project: &ProjectInfo,
) -> Result<(), String> {
    let intro_dir = format!("{}/meson-info", build_root);
    std::fs::create_dir_all(&intro_dir)
        .map_err(|e| format!("Cannot create introspection dir: {}", e))?;

    // intro-projectinfo.json
    let project_info = serde_json::json!({
        "descriptive_name": project.name,
        "version": project.version,
        "subproject_dir": project.subproject_dir,
        "subprojects": [],
    });
    std::fs::write(
        format!("{}/intro-projectinfo.json", intro_dir),
        serde_json::to_string_pretty(&project_info).unwrap(),
    )
    .map_err(|e| format!("Cannot write introspection: {}", e))?;

    // intro-targets.json
    let targets: Vec<serde_json::Value> = build_data
        .targets
        .iter()
        .map(|t| {
            serde_json::json!({
                "name": t.name,
                "id": t.id,
                "type": format!("{:?}", t.target_type).to_lowercase(),
                "defined_in": format!("{}/meson.build", t.subdir),
                "filename": [t.output_name],
                "build_by_default": t.build_by_default,
                "installed": t.install,
                "sources": t.sources,
            })
        })
        .collect();
    std::fs::write(
        format!("{}/intro-targets.json", intro_dir),
        serde_json::to_string_pretty(&serde_json::Value::Array(targets)).unwrap(),
    )
    .map_err(|e| format!("Cannot write introspection: {}", e))?;

    // intro-tests.json
    let tests: Vec<serde_json::Value> = build_data
        .tests
        .iter()
        .map(|t| {
            serde_json::json!({
                "name": t.name,
                "timeout": t.timeout,
                "suite": t.suite,
                "is_parallel": t.is_parallel,
                "protocol": t.protocol,
                "priority": t.priority,
            })
        })
        .collect();
    std::fs::write(
        format!("{}/intro-tests.json", intro_dir),
        serde_json::to_string_pretty(&serde_json::Value::Array(tests)).unwrap(),
    )
    .map_err(|e| format!("Cannot write introspection: {}", e))?;

    // intro-buildoptions.json
    std::fs::write(format!("{}/intro-buildoptions.json", intro_dir), "[]")
        .map_err(|e| format!("Cannot write introspection: {}", e))?;

    // intro-dependencies.json
    let deps: Vec<serde_json::Value> = build_data
        .dependencies
        .iter()
        .filter_map(|(name, obj)| {
            if let Object::Dependency(d) = obj {
                Some(serde_json::json!({
                    "name": name,
                    "version": d.version,
                    "compile_args": d.compile_args,
                    "link_args": d.link_args,
                }))
            } else {
                None
            }
        })
        .collect();
    std::fs::write(
        format!("{}/intro-dependencies.json", intro_dir),
        serde_json::to_string_pretty(&serde_json::Value::Array(deps)).unwrap(),
    )
    .map_err(|e| format!("Cannot write introspection: {}", e))?;

    // intro-installed.json
    std::fs::write(format!("{}/intro-installed.json", intro_dir), "{}")
        .map_err(|e| format!("Cannot write introspection: {}", e))?;

    // intro-benchmarks.json
    std::fs::write(format!("{}/intro-benchmarks.json", intro_dir), "[]")
        .map_err(|e| format!("Cannot write introspection: {}", e))?;

    Ok(())
}
